on:
  push:
    branches:
      - 'master'

name: Release Please

jobs:

  release-please:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          default-branch: 'master'

  after-release:
    needs:
      - release-please
    runs-on: ubuntu-latest
    steps:
      - name: do stuff
        run: echo ${{ needs.release-please.outputs.release_created }}
