on:
  push:
    tags:
      - 'v*.*.*'
  release:
    types:
      - published

name: Release

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: building
        run: echo "building"
