on:
  release:
    types:
      - published

permissions:
  contents: write

name: Release

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: building
        run: echo "something" > ./my-artifact

      - name: list
        run: ls -al

      - name: upload
        run: gh release upload ${{ github.event.release.tag_name }} ./my-artifact #super cool
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
