on:
  push:
    branches:
      - 'master'

name: Release Please

jobs:

  release-please:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          default-branch: 'master'
